#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidPageLayout.Resource", IsApplication=false)]

namespace AndroidPageLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int draggable_all_direction = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int draggable_bottom_direction = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int draggable_horizontal_direction = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int draggable_left_direction = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int draggable_right_direction = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int draggable_top_direction = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int draggable_vertical_direction = 2130771970;
			
			// aapt resource value: 0x7f010008
			public static int page_multi_size = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int page_orientation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int page_view = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int horizontal = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int linear_stack_layout = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int vertical = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int LinearStackLayout = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PageLayout = new int[] {
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public static int PageLayout_page_multi_size = 1;
			
			// aapt resource value: 0
			public static int PageLayout_page_orientation = 0;
			
			// aapt resource value: 2
			public static int PageLayout_page_view = 2;
			
			public static int[] SlideLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public static int SlideLayout_draggable_all_direction = 6;
			
			// aapt resource value: 1
			public static int SlideLayout_draggable_bottom_direction = 1;
			
			// aapt resource value: 5
			public static int SlideLayout_draggable_horizontal_direction = 5;
			
			// aapt resource value: 3
			public static int SlideLayout_draggable_left_direction = 3;
			
			// aapt resource value: 4
			public static int SlideLayout_draggable_right_direction = 4;
			
			// aapt resource value: 0
			public static int SlideLayout_draggable_top_direction = 0;
			
			// aapt resource value: 2
			public static int SlideLayout_draggable_vertical_direction = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
